name: favs-cron
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API routes to update favs/collective stats
        run: |
          curl --request GET \
          --url 'https://hodl-watch.vercel.app/api/favoritesManager?SECRET='${{env.CRYPTO_COMPARE_KEY}} \
          --header 'Authorization: Bearer ${{ env.CRYPTO_COMPARE_KEY }}'
